env_id: 2DBpp-v1
n_envs: 4
train_seed: 0
eval_seed: 10
total_timesteps: 3000000
n_eval_episodes: 20
log_dir: logs/ddqn
env_kwargs:
  render_mode: human
  bin_channels: 1
  items_per_bin: 15
  area_reward_coef: 0.4
  constant_penalty: -5.0
  action_fail: continue
  reward_type: compactness
monitor_kwargs:
  info_keywords: !!python/tuple
  - PE
policy_kwargs: &id001
  normalize_images: false
  network: CnnMlpNetwork1
  network_kwargs:
    hidden_dim: 200
DDQN_kwargs:
  policy: CnnMlpPolicy
  learning_rate: 0.001
  stats_window_size: 100
  policy_kwargs: *id001
  verbose: 1
  seed: 0
  device: auto
