env_id: 2DBpp-v4
n_envs: 4
train_seed: 0
eval_seed: 10
total_timesteps: 12500000
n_eval_episodes: 20
log_dir: logs/ddqn
env_kwargs:
  render_mode: human
  bin_channels: 1
  min_items_per_bin: 20
  max_items_per_bin: 30
  area_reward_coef: 0.4
  constant_penalty: -5.0
  action_fail: continue
  reward_type: compactness
monitor_kwargs:
  info_keywords: !!python/tuple
  - PE
policy_kwargs: &id001
  normalize_images: false
  network: CnnMlpNetwork4
  network_kwargs:
    hidden_dim: 1600
DDQN_kwargs:
  policy: CnnMlpPolicy
  buffer_size: 500000
  learning_rate: 0.001
  stats_window_size: 100
  policy_kwargs: *id001
  verbose: 1
  seed: 0
  device: auto
