env_id: 2DBpp-v3
n_envs: 4
train_seed: 0
eval_seed: 10
total_timesteps: 12500000
n_eval_episodes: 20
log_dir: logs/acktr
env_kwargs:
  render_mode: human
  bin_channels: 3
  items_per_bin: 25
  area_reward_coef: 0.4
  constant_penalty: -5.0
  action_fail: continue
  reward_type: area
monitor_kwargs:
  info_keywords: !!python/tuple
  - PE
policy_kwargs: &id001
  normalize_images: false
  network: CnnMlpNetwork3
  network_kwargs:
    hidden_dim: 1600
  dist_kwargs:
    mask_strategy: minus
    mask_minus_coef: 7
    mask_replace_coef: -7
    update_actor_stratrgy: masked
    entropy_strategy: naive
    invalid_probs_strategy: naive
  mask_type: predict
  ortho_init: false # must be false due to torch.linalg.eigh of kfac
ACKTR_kwargs:
  policy: CnnMlpPolicy
  learning_rate: 0.001
  n_steps: 64
  gamma: 0.99
  gae_lambda: 0.98
  vf_coef: 0.5
  max_grad_norm: 5
  stats_window_size: 100
  policy_kwargs: *id001
  verbose: 1
  seed: 0
  device: cpu # use cuda will cause error in kfac
  add_mask_loss: true
  mask_coef: 0.5
  add_entropy_loss: true
  ent_coef: 0.01
  add_invalid_probs: true
  invalid_probs_coef: 0.01
  acktr: true
